/*
 * *****************************************************************************
 * NAME: Tyler D Clark
 * PROJECT: Java 2D Graphics - PixelImage.java
 * COURSE: CMSC 405
 * DATE: 23 Jan 2021
 * *****************************************************************************
 */

package main.java;

import java.awt.*;
import java.awt.image.BufferedImage;

/**
 * Class to create simple 25 x 25 pixel images. Derived from the sample file BImage.java
 */
public class PixelImage {

  private static final int WHT = Color.WHITE.getRGB();
  private static final int CYN = Color.CYAN.getRGB();
  private static final int BLK = Color.BLACK.getRGB();
  private static final int RED = Color.RED.getRGB();

  public static int[][] letterT = {
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, RED, RED, RED, WHT, WHT},
    {WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, RED, RED, RED, WHT, WHT},
    {WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, RED, RED, RED, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT}};


  public static int[][] letterY = {
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT},
    {WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT},
    {WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT},
    {WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT},
    {WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT},
    {WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT},
    {WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT},
    {WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT},
    {WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT}};

  public static int[][] exclamationMark = {
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, CYN, CYN, CYN, BLK, BLK, BLK, RED, RED, RED, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT}};

  /**
   * Produces a BufferedImage from a 25 x 25 2D array
   * @param data - 2d array using the Color members defined in this class
   * @return the complete image
   */
  public BufferedImage getImage(int[][] data) {
      BufferedImage image = new BufferedImage(25, 25, BufferedImage.TYPE_INT_RGB);
      for (int y = 0; y < 25; y++) {
          for (int x = 0; x < 25; x++) {
              image.setRGB(x, y, data[x][y]);
          }
      }
      return image;
  }
}
